# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e34d030c5b90f45e73d6943f578bf0f74539625c7e7b30d00f63cc81a53fc27a7da13c77134d008692d23c08d0f1bfbaf8cf056fb7bc988efe35eb3c1ae2b635

test:
  secret_key_base: d225d9ad0698616b3c68612e956dbbfbc4839103f3cf2ec1f2406abbf3fb971aab33d43e6b2a1498b210439828b45285aaca98e43cf37421908df47028e9c964

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
